{{- range .Values.Namespaces }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: tenant-role-binding
  namespace: {{ include "tenant.namespace" (dict "ns" .name "g" $) }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: tenant-role
subjects:
  - namespace: {{ include "tenant.namespace" (dict "ns" .name "g" $) }}
    kind: ServiceAccount
    name: {{ include "tenant.name" $ }}
{{- end -}}