{{- range .Values.Namespaces }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "tenant.name" $ }}
  namespace: {{ include "tenant.namespace" (dict "ns" .name "g" $) }}
{{- end }}