name: Build and push Docker image to dockerhub

on:
  push:
    branches:
      - 'main'

env:
  IMAGE_NAME: andreasbomholtz/development

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out the repo
      uses: actions/checkout@v4

    - name: Login to dockerhub
      uses: docker/login-action@v3
      with:
       username: ${{ secrets.DOCKERHUB_USERNAME }}
       password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Get next version
      uses: actions-tools/yaml-outputs@v2
      id: yaml
      with:
        file-path: './charts/12factor/Chart.yaml'

    - name: Build and push to dockerhub
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        tags: "${{ env.IMAGE_NAME }}:${{ steps.yaml.outputs.version }}"

    - name: Update Chart.yaml with new version
      uses: mikefarah/yq@master
      with:
        cmd: yq -i '.version = "${{ steps.yaml.outputs.version }}" | .appVersion = "${{ steps.yaml.outputs.version }}"' ./charts/12factor/Chart.yaml

    - name: Commit the changes to Chart.yaml
      uses: devops-infra/action-commit-push@master
      with:
        github_token: "${{ secrets.GITHUB_TOKEN }}"
        commit_prefix: "[AUTO]"
        commit_message: "Automatic commit"